# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now we have gathered all the required skills needed to solve systems of linear equations. We saw why need to calculate inverses of matrices, followed by matrix multiplication to figure the values of unknown variables. 

Following exercises present some problems that can be converted into a system of linear equations. Solve the problems for the values of unknown variables. 

## Objectives
You will be able to:

* Build a system of equations from given problem by creating matrix and vectors in NumPy
* Calculate the inverse and dot-product to get the values for unknown variables.
* Solve linear equations using `numpy.linalg.solve()`

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea was sold, giving a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [4]:
# Solution:
# original equation:
# 29c + 41t = 490
# 23c + 41t = 448

# subtract the first equation from the second equation and result is:
# 6c = 42
# so c = 7

# plug the value for variable c back into the original equation:
# 29(7) + 41t = 490
# 203 + 41t = 490
# 41t + 490-203
# 41t = 287
# t = 7

#import Numpy
import numpy as np

# define A and B
A = np.matrix([[29,41],[23,41]])
B = np.matrix([490,448])

# take the inverse of matrix A
A_inv = np.linalg.inv(A)
A_inv

matrix([[ 0.16666667, -0.16666667],
        [-0.09349593,  0.11788618]])

In [5]:
#check the shape of B
print(B.shape)
B = B.T
print(B.shape)
B

(1, 2)
(2, 1)


matrix([[490],
        [448]])

In [6]:
X = A_inv.dot(B)
X

matrix([[7.],
        [7.]])

In [13]:
# Explain your answer in terms of prices
# so the result of the equation and the multiplication of the matrices
# shows that a bag of coffee equals $7 and bag of tea also euqals $7.
# The linear equation is solved as the mutliplication of the "pricing" matrix [29,41] and [23,41]
# and the other side of the equation is the total dollar amount matrix [490,448]
# to get the final solution we need to multiply the first set of matrices by their negative -1 exponent which is
# the same as dividing the right hand side of the equation ([490,448]) by the first matrix ([29,41],[23,41])
# the resulting multiplication code above provides our answer of $7 for bag of coffee and $7 for bag of tea.

## Exercise 2:

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in another music concert. 

How much was the admission for each child and adult?

In [8]:
# Create a system of equations
# 12c + 3a = 162
# 8c + 3a = 122

# or in matrix format:
A = np.matrix([[12,3],[8,3]])
B = np.matrix([162,122])

A_inv = np.linalg.inv(A)
print(A_inv)

print(B.shape)
B = B.T
print(B.shape)
B

X = A_inv.dot(B)
X

[[ 0.25       -0.25      ]
 [-0.66666667  1.        ]]
(1, 2)
(2, 1)


matrix([[10.],
        [14.]])

In [7]:
# Describe your result
# shows that a ticket for a child is $10 and an adult ticket is $14
# The linear equation is solved as the mutliplication of the "price" matrix [12,3] and [8,3]
# and the other side of the equation is the total dollar amount matrix [162,122]
# to get the final solution we need to multiply the first set of matrices by their negative -1 exponent which is
# the same as dividing the right hand side of the equation ([162,122]) by the first matrix ([12,3],[8,3])
# the resulting multiplication code above provides our answer of $10 for a child ticket and $14 for an adult ticket.

## Exercise 3:

You want to make a certain kind of tropical punch, using bananas, oranges, and papayas. 

Suppose you don't know how many of each to put in the punch, but you know that there are seven pieces of fruit in the mix, and there are twice as many oranges as bananas. 

You also know that the seven pieces of fruit cost \$5.25, 

where bananas cost \$.50 each, oranges cost \$.75 each, and papayas cost \$1.25 each.

How many bananas, oranges and papayas would you need to make this punch ?

In [10]:
# Create a system of equations
# b + 2o + p = 7
# .5b + .75o + 1.25p = 5.25

# mutliply the second part of the equation by 2

# b + 2o + p = 7
# b + 1.5o + 2.5p = 10.5
# -2o + o + p = 0

# or in matrix format

import numpy as np

A = np.matrix([[1,1,1],[.5,.75,1.25],[-2,1,0]])
B = np.matrix([7,5.25,0])

A_inv = np.linalg.inv(A)
print(A_inv)

print(B.shape)
B = B.T
print(B.shape)
B

X = np.linalg.solve(A,B)
X

[[ 0.71428571 -0.57142857 -0.28571429]
 [ 1.42857143 -1.14285714  0.42857143]
 [-1.14285714  1.71428571 -0.14285714]]
(1, 3)
(3, 1)


matrix([[2.],
        [4.],
        [1.]])

In [2]:
# Explain your answer
# The system of equations represents the 3 versions in the question with the associated 3 column, 3 row matrix
# The system is then solved for b=2, o=4 and p=1
# This is then proved by substituting in the first equation:
# b + 2o + p = 7 OR
# 2 + 2(2) + 1 = 7 OR
# 2 + 4 + 1 = 7
# 7 = 7

## Exercise 4

A landlord owns 3 houses, a 1-bedroom, a 2-bedroom , and a 3-bedroom house. 

The total rent he receives is 1240 dollars. 

He needs to make some repairs, where it costs 10% of the 1-bedroom house’s rent for its repairs, 20% of the 2-bedroom for its repairs, and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was $276. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [12]:
# Create a system of equations

# a = 1 bedroom house, b = 2 bedroom house, c = 3 bedroom house
# a + b + c = 1240
# .10a + .20b + .30c = 276
# 2a + b - c = 0 

# or in matrix format

A = np.matrix([[1,1,1],[.10,.20,.30],[2,0,-1]])
B = np.matrix([1240,276,0])

A_inv = np.linalg.inv(A)
print(A_inv)

print(B.shape)
B = B.T
print(B.shape)
B

X = np.linalg.solve(A,B)
X


[[ -2.  10.   1.]
 [  7. -30.  -2.]
 [ -4.  20.   1.]]
(1, 3)
(3, 1)


matrix([[280.],
        [400.],
        [560.]])

In [11]:
# Explain your answer
# The system of equations represents the 3 versions in the question with the associated 3 column, 3 row matrix
# a = 1 bedroom house, b = 2 bedroom house and c = 3 bedroom house
# The system is then solved for a=280, b=400 and c=560
# This is then proved by substituting in the first equation:
# a + b + c = 1240
# 280 + 400 + 560 = 1240 or the second equation:
# .10a + .20b + .30c = 276
# .10(280) + .20(400) + .30(560) = 276
# 28 + 80 + 168 = 276
# 276 = 276

## Summary
In this lab, we saw how to use Numpy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `.solve()`. We shall now take these skills forward and see how we can define a simple regression problem using linear algebra and solve it with numpy, only using the skills that we have learnt so far. 